# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dockernetcoreapi:
    image: dockernetcoreapi
    build:
      context: .
      dockerfile: DockerNetCoreAPI/Dockerfile
    ports:
      - 8081:8081
