version: '3.9'

services:

  # SQL Server 2022 Service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - 1433:1433
    # volumes:
    #   - ./sqlserver_data:/var/opt/mssql
    networks:
      - web_network

  # dotnet webapi service
  api:
    depends_on:
      - db
    build: ./
    container_name: webapi
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8081:80
    networks:
      - web_network

networks:
  web_network:
    name: netcore_network
    driver: bridge